
services: 
  node-app:
  #  build: 
  #   context: .
   image: 445567096663.dkr.ecr.us-east-1.amazonaws.com/node-app:lastest
   depends_on:
    - postgres-db
   restart: "no"
   environment:
    NODE_ENV: "production"
    DB_HOST: "postgres-db"
    DB_USER: "dubby"
    DB_PASS: "dubby1"
    DB_NAME: "postgres-db"
    DB_PORT: 5432
    PORT: 5051
   ports:
    - 5004:5051
   volumes: 
    - .:/www/app
    -  /usr/src/app/node_modules 
   networks:
    - altsch-network 

  postgres-db:
   image: postgres
   ports:
    - 5432:5432
   environment:
    POSTGRES_PASSWORD: dubby1
    POSTGRES_USER: dubby
    POSTGRES_DB: "postgres-db"
   networks:
    - altsch-network   

networks:
  altsch-network:
   name: altsch-network
   driver: bridge

